### ISSUE TITLE
Names that are too long

### ISSUE THREAD

**Issue by Sothatsit** [drtnf/threeChess#4]
Hello, when the player names are too long they can go off the screen or under the board. Not really sure the best way to fix this.

![Screen Shot 2020-09-23 at 4 22 00 Integration](https://user-images.githubusercontent.com/1185881/93986320-c8080500-fdb8-11ea-894c-d07773740dcf.png)

**Comment by drtnf** [comment]
Could rotate those Strings by 60 degrees, or truncate names at 10 chars (or both?)

**Comment by Sothatsit** [comment]
Made a PR: https://github.com/drtnf/threeChess/pull/7
