### ISSUE TITLE
NullPointerException in Board.getPositions()

### ISSUE THREAD

**Issue by xfolland** [drtnf/threeChess#6]
When calling the getPositions() method in Board.java you may receive a null pointer exception:

Exception in thread "main" java.lang.NullPointerException
&nbsp;&nbsp;&nbsp;&nbsp;at threeChess.Board.getPositions(Board.java:64)
&nbsp;&nbsp;&nbsp;&nbsp;at threeChess.agents.RandomAgent.playMove(RandomAgent.java:38)
&nbsp;&nbsp;&nbsp;&nbsp;at threeChess.ThreeChess.play(ThreeChess.java:148)
&nbsp;&nbsp;&nbsp;&nbsp;at threeChess.ThreeChess.tournament(ThreeChess.java:107)
&nbsp;&nbsp;&nbsp;&nbsp;at threeChess.ThreeChess.main(ThreeChess.java:211)

This bug can be reproduced by calling getPositions() a large number of times. The simplest way to reproduce is to change line 211 in ThreeChess.java to `else tournament(bots,300,1000,false,null);` to quickly run a large number of games (and therefore create a large number of calls to getPositions()).

**Comment by drtnf** [comment]
I've resolved this issue. It turns out, in rare cases the King was thought to be castling when it was not on the back rank.
